name: Do test and lint

on:
  pull_request:
    types: [opened, synchronize]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go build

    - name: Test
      run: go test -v -race ./...
      
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
          version: v1.33.0
